#!/usr/bin/env php
<?php

use Illuminate\Contracts\Console\Kernel;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
if (file_exists($autoloader = __DIR__.'/vendor/autoload.php')) {
    require $autoloader;
}

// Bootstrap Laravel and handle the command...
if (file_exists($app_path = __DIR__.'/bootstrap/app.php')) {
    $app = require_once $app_path;
    $kernel = $app->make(Kernel::class);

    $status = $kernel->handle(
        $input = new Symfony\Component\Console\Input\ArgvInput,
        new Symfony\Component\Console\Output\ConsoleOutput
    );

    $kernel->terminate($input, $status);

    exit($status);
} else {
    echo "Bootstrap file not found. Project may be incomplete.\n";
    exit(1);
}
